version: "3"

services:
  postgres:
    container_name: postgres
    image: "postgres:12"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    container_name: redis
    image: "redis:6.0"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  elasticsearch:
    container_name: elasticsearch
    image: "elasticsearch:5"
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  jobs:
    container_name: jobs
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/om30'
      - gems:/gems
    environment:
      RAILS_ENV: production

  app:
    container_name: app
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    volumes:
      - .:/om30
      - gems:/gems
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
      RAILS_ENV: production
    ports:
      - 3000
  
  proxy:
    container_name: proxy
    image: dbnkocao/proxy:apache
    depends_on:
      - app
    volumes:
      - proxy:/etc/apache2
    ports:
      - 80:80

volumes:
  redis:
  postgres:
  gems:
  elastic:
  proxy: