version: "3"

services:
  postgres:
    image: "postgres:12"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: "redis:6.0"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  elasticsearch:
    image: "elasticsearch:5"
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/om30'
      - gems:/gems
    environment:
      RAILS_ENV: production

  app:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: bash start.sh
    volumes:
      - .:/om30
      - gems:/gems
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
      RAILS_ENV: production

volumes:
  redis:
  postgres:
  gems:
  elastic: